### ISSUE TITLE
Console application not using correct bugsnag library

### ISSUE THREAD

**Issue by tholder** [wrep/bugsnag-php-symfony#10]
See https://github.com/wrep/bugsnag-php-symfony/blob/master/Console/BugsnagConsoleApplication.php#L26

This code should be using Bugsnag_Client

**Comment by joaonice** [comment]
This bundle is deprecated, it still uses bugsnag v1.0.9.

**Comment by mac-cain13** [comment]
Yeah @joaonice is correct. We don't maintain this anymore.

I've added a notice to the Readme and I'm afraid you should look into an alternative. Sorry!
